[package]
name = "datagen"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
monty = { path = "../", features = ["datagen"] }
montyformat = { git = 'https://github.com/jw1912/montyformat.git' }
