[package]
name = "value"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
goober = { git = 'https://github.com/jw1912/goober' }
montyformat = { git = 'https://github.com/official-monty/montyformat.git', tag = "v0.3.0" }
