[package]
name = "datagen"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting, Viren & The Monty Authors"]

[dependencies]
montyformat = { workspace = true }
monty = { workspace = true, features = ["datagen"] }

[features]
default = []
value   = ["monty/value"]
policy  = ["monty/policy"]
