[package]
name = "train"
version = "1.0.0"
edition = "2021"
authors = ["Jamie Whiting"]
rust-version = "1.83"

[dependencies]
bullet = { package = "bullet_lib", git = 'https://github.com/jw1912/bullet' }
monty = { path = "../", package = "monty" }
